<div class="custom-submenu">
  <ul id="services">
    <li class="category" id="web">
      <h4>Web</h4>
      <ul class="products">
        <li class="product"><a href="/contact/small-site"><abbr title="Custom Design based on a fixed set of drupal features">Small Site</abbr></a></li>
        <li class="product"><a href="/contact/drupal-theming"><abbr title="Design &amp;/or theme for an existing site">Drupal Theme</abbr></a></li>
        <li class="product"><a href="/contact/full-service-design-development"><abbr title="Custom Design, Functionality, and Theming">Full Service Design &amp; Development</abbr></a></li>
        <!--<li class="product"><a href="/contact/website-planning"><abbr title="&ldquo;I need to build this in Drupal. How do I do that?&rdquo;">Website Planning</abbr></a></li>-->
        <li class="product"><a href="/contact/finish-my-site-theming-site-building"><abbr title="&ldquo;I need to finish this Drupal site. Can you help?&rdquo;">Finish My Site</abbr></a></li>
      </ul>
    </li>
    <li class="category" id="promotion">
      <h4>Promotion</h4>
      <ul class="products">
        <li class="product"><a href="/contact/promotion"><abbr title="">Media Relations</abbr></a></li>
        <li class="product"><a href="/contact/promotion"><abbr title="">Marketing, Outreach &amp; Social Media</abbr></a></li>
        <!--
        <li class="product"><a href="/contact/promotion"><abbr title="">Social Media</abbr></a></li>
        <li class="product"><a href="/contact/promotion"><abbr title="">Consultation</abbr></a></li>
        -->
      </ul>
    </li>
    <li id="general" class="category">
      <h4><a href="/contact">Or Just Say &ldquo;Hi!&rdquo;</a></h4>
    </li>
  </ul>
</div>
