<div class="custom-submenu">
  <ul id="services">
    <li class="category" id="promotion">
      <h4>Promotion</h4>
      <ul class="products">
        <li class="product"><a href="/services/media-relations"><abbr title="">Media Relations</abbr></a></li>
        <li class="product"><a href="/services/marketing-outreach-social-media"><abbr title="">Marketing, Outreach &amp; Social Media</abbr></a></li>
        <li class="product"><a href="/services/consulting-communications-strategy"><abbr title="">Consulting &amp; Communications Strategy</abbr></a></li>
        <!--
        <li class="product"><a href="/contact/promotion"><abbr title="">Social Media</abbr></a></li>
        <li class="product"><a href="/contact/promotion"><abbr title="">Consultation</abbr></a></li>
        -->
      </ul>
    </li>
  </ul>
</div>
