<?php
/**
 * Implementation of hook_views_api().
 */
function canaryviews_views_api() {
  return array(
    'api' => 2,
    //'path' => drupal_get_path('module', 'canaryviews'),
    'path' => drupal_get_path('module', 'canaryviews') . '/includes',
  );
}

function canaryviews_views_default_views(){
  $views = array();
  $files = file_scan_directory(drupal_get_path('module', 'canaryviews'). '/includes', '.inc');
  foreach ($files as $absolute => $file) {
    require $absolute;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}